---
- hosts: docker
  vars_files:
    - vars.yml
  gather_facts: true
  sudo: true

  tasks:
  - name: Stop docker container
    command: docker stop tangy-mongo-1
    ignore_errors: yes

  - name: Remove docker container
    command: docker rm tangy-mongo-1
    ignore_errors: yes

  - name: Pull the docker image from docker hub
    command: docker pull andutta/tangy-mongo-1.0

  - name: Start docker container
    command: docker run -d -p 9099:9099 -e HOST_NAME={{inventory_hostname}} -e DB_SERVER=192.168.2.8 -e SERVER_PORT=9099 -e CONSUL_HOST=192.168.2.8 --name tangy-mongo-1 andutta/tangy-mongo-1.0

